server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.jackson.deserialization.accept-float-as-int=false
payment.supported-currencies=USD,EUR,GBP
payment.encryption.secret=${PAYMENT_ENCRYPTION_SECRET:local-development-secret}
payment.encryption.salt=${PAYMENT_ENCRYPTION_SALT:5c0744940b5c369b}
bank-simulator.payments-url=http://localhost:8080/payments
